### ISSUE TITLE
Remove lines from circle.yml

### ISSUE THREAD

**Issue by davidcpell** [kung-fu-pandas/photogram#4]
I think [lines 2-4](https://github.com/kung-fu-pandas/photogram/blob/master/circle.yml#L2-L4) in `circle.yml` are superfluous since `bin/setup` in line 7 will set up the db with `bin/rake dev:prime`. Prime depends on `db:setup`:

````
task prime: "db:setup" do
    include FactoryGirl::Syntax::Methods

    # create(:user, email: "user@example.com", password: "password")
end 
````

**Comment by sstgithub** [comment]
Tried CircleCI (build 20)[https://circleci.com/gh/kung-fu-pandas/photogram/20] and (build 21)[https://circleci.com/gh/kung-fu-pandas/photogram/21] to get this to work without those commands but the `simpleform` gem prevents it from working. Do you think it would be better to leave it or to run `bin/setup` and `rails generate simpleform:install` instead of the rake commands?

**Comment by davidcpell** [comment]
So it's not actually `simpleform` that is causing the problem (that's just a warning) but the lack of a `schema.rb` file:

```
/home/ubuntu/photogram/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /home/ubuntu/photogram/config/application.rb to limit the frameworks that will be loaded.
```

It looks like I was wrong about how `rake db:setup` works. It looks like it first runs `rake db:schema:load` (the part that requires a `schema.rb` file) and then `rake db:seed`. I thought it did `rake db:create db:migrate db:seed`. 

With that said, I guess what I still don't understand why the `circle.yml` file needed to be updated. Why would `suspenders` bootstrap the app with a CI config that doesn't work?

**Comment by davidcpell** [comment]
closing for now
